<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>AsgerB</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <link href="css.css" rel="stylesheet" type="text/css">
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>
    </head>
    <body id='page'>
        <div id="container">
            <header><img src="AsgerB.png"></header>
            <div id="replace-nav"></div>
            <nav id="navbar">
                <div id="banner">AsgerB</div>
                <div id="mobile-select">|||</div>
                <ul id="navbar-list">
                    <li><a href="index.php">Home</a></li>
                    <li><a href="about.php">About</a></li>
                    <li><a href="contact.php">Contact</a></li>
                    <li id="projects">Projects
                        <ul>
                            <li><a href="http://asgerb.net/keygame/">KeyGame</a></li>
                            <li>Meow</li>
                            <li>Meow</li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <main>