<nav id="navbar">
    <div id="mobile-select">|||</div>
    <ul id="navbar-list">
        <li><a href="index.html">Home</a></li>
        <li><a href="index.html">About</a></li>
        <li><a href="contact.html">Contact</a></li>
        <li id="projects">Projects
            <ul>
                <li>Meow</li>
                <li>Meow</li>
                <li>Meow</li>
            </ul>
        </li>
    </ul>
</nav>